language: c
before_script: ./autogen.sh

os:
  - linux
  - osx  

compile:
  - clang
  - gcc

branches:
  only:
    - master

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -qq autotools-dev autoconf automake pkg-config libtool ; fi

script: 
  - ./configure 
  - make 
  - make check

after_failure:
  - cat ./test/*.log ./src/math/*.log
