language: c
before_script: ./autogen.sh

os:
  - linux
  - osx  

compile:
  - clang
  - gcc

branches:
  only:
    - master

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install autoconf automake libtool ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then apt-get install -qq autotools-dev autoconf automake pkg-config libtool ; fi

script: 
  - ./configure 
  - make 
  - make -j 4 check 
