/* Generated by CMake. */

#cmakedefine HAVE_APPLICATIONSERVICES_APPLICATIONSERVICES_H 1
#cmakedefine HAVE_DIRENT_H 1
#cmakedefine HAVE_DLFCN_H 1
#cmakedefine HAVE_FMAX 1
#cmakedefine HAVE_FMIN 1
#cmakedefine HAVE_GTK 1
#cmakedefine HAVE_INTTYPES_H 1
#cmakedefine HAVE_JPEGLIB_H 1
#cmakedefine HAVE_LIBM 1
#cmakedefine HAVE_LIBREADLINE 1
#cmakedefine HAVE_LONG_DOUBLE 1
#cmakedefine HAVE_LONG_DOUBLE_WIDER 1
#cmakedefine HAVE_MPI 1
#cmakedefine HAVE_NDIR_H 1
#cmakedefine HAVE_PNG_H 1
#cmakedefine HAVE_PTHREAD_H 1
#cmakedefine HAVE_STDINT_H 1
#cmakedefine HAVE_STDIO_H 1
#cmakedefine HAVE_STDLIB_H 1
#cmakedefine HAVE_STRINGS_H 1
#cmakedefine HAVE_STRING_H 1
#cmakedefine HAVE_SYS_DIR_H 1
#cmakedefine HAVE_SYS_NDIR_H 1
#cmakedefine HAVE_SYS_STAT_H 1
#cmakedefine HAVE_SYS_TIME_H 1
#cmakedefine HAVE_SYS_TYPES_H 1
#cmakedefine HAVE_TRUNC 1
#cmakedefine HAVE_UNISTD_H 1
#cmakedefine OS_DARWIN 1
#cmakedefine OS_LINUX 1
#cmakedefine STDC_HEADERS 1
#cmakedefine TIME_WITH_SYS_TIME 1

#define PACKAGE "raygay"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_NAME "RayGay"
#define PACKAGE_STRING "RayGay @PROJECT_VERSION@"
#define PACKAGE_TARNAME "raygay"
#define PACKAGE_URL ""
#define PACKAGE_VERSION "@PROJECT_VERSION@"
#define VERSION "@PROJECT_VERSION@"

#if defined(__BIG_ENDIAN__)
#define WORDS_BIGENDIAN 1
#endif
